# To create, use conda env create:
# conda env create --file environment.yml
# To update, recreate from scratch (due to issues with --prune option):
# conda env create --file environment.yml --force
name: d22a-mcdc
channels:
  - conda-forge
  - defaults
dependencies:
  - notebook
  - cdo=2.*.*
  - matplotlib
  - xarray
  - NetCDF4
  - python-cdo=1.5.*
  - scipy
  - statsmodels
